name: Deploy Project

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    env:
      TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Build Vite app
      run: npm run build

    # --- AWS Credentials (for Terraform backend) ---
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1

    # --- Terraform ---
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform -chdir=infra init

    - name: Terraform Plan
      run: terraform -chdir=infra plan

    - name: Terraform Apply
      run: terraform -chdir=infra apply -auto-approve

    # --- Wrangler Deploy ---
    - name: Install Wrangler
      run: npm install -g wrangler

    - name: Deploy to Cloudflare Pages
      run: wrangler pages deploy dist/frontend --project-name=ragdoll-frontend
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # Needs to be explicitly passed here
